### ISSUE TITLE
curl is only available on Windows 10 build 17063 or higher

### ISSUE THREAD

**Issue by LeedsDBA** [Microsoft/sqlworkshops#10]
Update documentation to highlight that curl is only available in Windows 10 build 17063 or higher. For a couple of my team their version was too low. Might be worth highlighting on the prerequisites too.

Workaround: just download the file manually.

https://blogs.msdn.microsoft.com/commandline/2018/01/18/tar-and-curl-come-to-windows/

**Comment by BuckWoody** [comment]
Noted. Fixed in Module 04.
