### ISSUE TITLE
Feedback for G2C Module 00

### ISSUE THREAD

**Issue by BuckWoody** [microsoft/sqlworkshops#104]
Module: 
https://github.com/microsoft/sqlworkshops/blob/master/SQLGroundToCloud/sqlgroundtocloud/00-prerequisites.md

Section: 
Activity 4: Set up your environment for Modules 4 and 5
Important Note! If you are being provided an account by your instructor (see Option 4 in Activity 1), you do not need to complete this activity.

Before arriving at the workshop, if you intend to complete 04-SQLServerOnTheMicrosoftAzurePlatform and/or 05-MigratingToAzureSQL, you must complete the prerequisites outlined here. Note that all screenshots are provided, so you can "audit" this part of the Workshop if you like.

Change Proposed:
The pre-reqs link from here points to a series of steps, one of which has the name/password pair. Recommend pulling the password and

**Comment by amthomas46** [comment]
@BuckWoody Nice catch. I can remove the password but what was the "And … " referring to at the end?

**Comment by amthomas46** [comment]
@BuckWoody I think I've addressed this, thanks! 

https://github.com/microsoft/sqlworkshops/compare/anna?expand=1
