### ISSUE TITLE
Feedback for G2C Module 02

### ISSUE THREAD

**Issue by BuckWoody** [microsoft/sqlworkshops#105]
Module: 
https://github.com/microsoft/sqlworkshops/blob/master/SQLGroundToCloud/sqlgroundtocloud/02-ModernizingYourDataEstateWithSQLServer2019.md

Section: 
SELF-PACED USERS ONLY: If you are using this module self-paced, read the overview of SQL Server 2019 from SQL Server 2019 of the SQL Server 2019 Lab and then proceed to Module 2.1 of this workshop SQL Server 2019 Intelligent Performance. NOTE: The SQL Server 2019 lab has Next Steps. Do not follow those but read the introduction and come back to the next section of this workshop.

Change Proposed:
The line "NOTE: The SQL Server...." should be on it's own line. If you add this as the Markdown: 

<pre>
> **NOTE:** The SQL Server....
</pre>

It will indent and format nicely.  

---------------------------
Section: 
Instructor led workshops will review Intelligent Performance in SQL Server 2019 using the Module 2.1 Intelligent Performance Section from the deck SQL Server 2019 Modern Data Platform

Change Proposed:
Replace "Deck" with "PowerPoint Slides"

---------------------------
Section: 
Activity: SQL Server Intelligent Performance
Proceed directly to the following Activities...

Change Proposed:

Open the following Activities from Module SQL Server 2019 Security of the SQL Server 2019 Lab in another tab in your browser, for a hands-on exercise. When are you done with these activities come back here for the next section as guided by your instructor.

---------------------------
Section: 
2.6 What Else, Migration, and Next Steps

Change Proposed:
2.6 Additional Improvements, Migration, and Next Steps

**Comment by rgward** [comment]
Thanks for the suggestions. Fixes in next PR
