### ISSUE TITLE
Feedback for G2C Module 02 Structure Pass

### ISSUE THREAD

**Issue by BuckWoody** [microsoft/sqlworkshops#106]
Module: 
https://github.com/microsoft/sqlworkshops/blob/master/SQLGroundToCloud/sqlgroundtocloud/02-ModernizingYourDataEstateWithSQLServer2019.md

---------------------------
Section: 
https://github.com/microsoft/sqlworkshops/blob/master/sql2019lab/03_Availability.md#activityadr

Change Proposed:
I think the bookmark isn't rendering correctly. When you click it, you have to scroll down a bit to see the actual activity. Not a deal-breaker, but could be confusing.

---------------------------
Section: 
as guided by your instructor.
Activity: Using Polybase with Azure SQL Server Database

Change Proposed:
Same comment as above. Bookmarks do not appear to jump to the proper location

**Comment by rgward** [comment]
I don't see the problem with these links

**Comment by rgward** [comment]
this appears to be a problem with the Edge browser. At this point we don't have a fix.
