### ISSUE TITLE
Feedback for SQLG2C for section 4.3 of Module 4

### ISSUE THREAD

**Issue by rgward** [microsoft/sqlworkshops#108]
Feedback for Section 4.3 of Module 4 at https://github.com/microsoft/sqlworkshops/blob/master/SQLGroundToCloud/sqlgroundtocloud/04-SQLServerOnTheMicrosoftAzurePlatform.md

Module 4 feedback for 4.3

=========

They're feeling more comfortable with the networking and security aspects as well

But we really didn't talk about security except for links right?

========

Convert	Convert the source schema to work in the target environment. This is only relevant for heterogeneous migrations.	
SQL Server Migration Assistant

You say heterogeneous but make sure they know this is only for non SQL Server sources

=========

Online migrations with DMS

Are these the right links?

Online migrations with DMS
Offline migrations with DMS

=========

Sync data

Data sync just for thoroughness with the diagram

========

Remediate applications	Iteratively make any necessary changes to your applications.	

Any guidance here?

========

I forgot what the diagram looked like after going through the table

========

Above is a survey of some of the resources and tips available for going through the migration journey to Azure (you can find a full list of tools based on phase and target here).

Don't get overwhelmed, the number of resources shows the dedication Microsoft and partners have to helping you move successfully to the cloud. We recommend using the Data migration guide which allows you to pick your source and target, and then guides you step-by-step through your specific migration journey.

Maybe this should go up front and the table is only a reference list. I got lost going through the table. I honest was overwhelmed<g>. There were a bunch of tools and resources listed but it was not clear which ones I should focus on vs looking through all of them.

=====

**Comment by amthomas46** [comment]
* Removed "They're feeling more comfortable with the networking and security aspects as well"
* Changed to "This is only relevant for heterogeneous (non-SQL Server) migrations."
* Fixed online and offline migration links
* Sync data to data sync
* Added link for app migration info and samples
* Moved chart to bottom and wording to refer to it as a reference  


Thanks!
