### ISSUE TITLE
Feedback for main page for SQL G2C

### ISSUE THREAD

**Issue by rgward** [microsoft/sqlworkshops#112]
Here is some feedback for the main page of SQLG2C at https://github.com/microsoft/sqlworkshops/tree/master/SQLGroundToCloud

Feedback for main page of SQLG2C

====

you'll gain a deep understanding on the latest SQL Server engine and how you can use it to solve real-world challenges.

Not sure we should use the word deep or even latest SQL Server engine

how about "you learn how SQL Server 2019 and Azure SQL solve real-world challenges"

====

(You can view all of the source files for this workshop on this GitHub site, along with other workshops as well. Open this link in a new tab to find out more.)

I'm not sure this has the right link?

=====

General comment about the Abstract

Do we need an abstract? I thought the About the Workshop did a good job of describing the workshop?

=====

If you keep it...

Members from the Azure Data Product Group will lead you through the data estate options from Microsoft, from on-premises SQL Server (including some of the new features in SQL Server) to Relational Database options in Azure.

What is this is taught by someone else?

=====

You'll how to evaluate the benefits/costs of each technology option

I think the sentence is missing a word here. But also we really don't teach costs in this workshop?

====

In this day-long, hands-on workshop you’ll learn how to:

Someone may just teach parts of it. I would avoid saying day-long

=====

Articulate the key differentiators between SQL Server on-prem, in Azure VM, in Azure SQL DB, and hybrid configurations

I would use Anna's term of Azure SQL so perhaps

...between SQL Server on-prem, Azure SQL, and hybrid configurations

on that point we aren't teaching much hybrid though in this workshop (at least today) right?

=====

Understand how Azure SQL DB is secured and address security concerns

I would use the word Azure SQL throughout this. 

Also "addresses instead of address"

=====

Understand additional Azure platform features for data pipelines and security

I don't think we cover this?

=====

SQL Server Virtual Machines in Microsoft Azure	Covers the tools, processes and procedures for SQL Server Virtual Machines on the Microsoft Azure platform

After reading Module 4 this to me overstates what we are presenting on SQL VM

We can get Anna to modify or come up with something a bit more realistic since she really only barely touches on SQL VM

=====

Azure SQL Database	Covers the tools, processes and procedures for Azure SQL Database (Managed Instance, Singleton, and Elastic Pools)

To line up with Anna's module terminology, I think this should say

..."for Azure SQL Database (Managed Instance, Single Database, and Elastic Pool)

=====

"What to Use When"	Teaches a complete set of tools and processes used to determine the best architecture for a given customer scenario on the Microsoft Azure platform

I haven't reviewed Module 6 yet but will it also talk about when to use SQL Server 2019 not just Azure?

=====

You'll need a local system that you are able to install software on.

You say in the same paragraph you can use Azure VM but folks might see the first sentence and think they HAVE to do this on a local server or laptop

====

You must have a Microsoft Azure account with the ability to create assets, specifically the Azure Kubernetes Service (AKS).

Since we are not doing a BDC hands-on exercise why is ths required?

====

This workshop expects that you understand data structures and working with SQL Server and computer networks. This workshop does not expect you to have any prior data science knowledge, but a basic knowledge of statistics and data science is helpful in the Data Science sections. Knowledge of SQL Server, Azure Data and AI services, Python, and Jupyter Notebooks is recommended. AI techniques are implemented in Python packages. Solution templates are implemented using Azure services, development tools, and SDKs. You should have experience working with the Microsoft Azure Platform.

Can rethink this a bit? In my mind what is really needed for this workshop is a basic working knowledge of SQL Server and tools like SSMS.

For example we say in this sentence

 Knowledge of SQL Server, Azure Data and AI services, Python, and Jupyter Notebooks is recommended.

I don't even have a knowledge of AI services or Jupyter Notebooks.

There is no "Data Science section" is there?

For Solution Templates do you mean Module 6. If you have to have experience with Azure is that only required for Module 6. We should say that then in my opinion.

=====

Remember to turn off any Virtual Machines from the Azure Portal 

Do you mean "delete"?

=====

Workshop Details
This workshop uses SQL Server Management Studio, Azure Data Studio, Microsoft Azure, and SQL Server (2019 and higher) with a focus on architecture and implementation.

I read this and didn't think it was really "details". Do we even need this section?

======

The times shown below are for an instructor-led course, you may also take the modules in a self-paced fashion.

But we just said in the section above this is Type: In-Person?

======

On the Workshop Modules and In-Class Agenda with the links I had people at Ready start to click on these without going down to the other parts of the page. Perhaps state something about these are the modules and you can view each one but to take the overall course keep reading or something like that

**Comment by BuckWoody** [comment]
Nicely done! Fixed all these - great suggestions.
