### ISSUE TITLE
Feedback for Module 00 for SQLG2C

### ISSUE THREAD

**Issue by rgward** [microsoft/sqlworkshops#113]
Feedback and issues for Module 00 at https://github.com/microsoft/sqlworkshops/blob/master/SQLGroundToCloud/sqlgroundtocloud/00-prerequisites.md

=====

but ensure that you turn off any VM's in the Portal 

There is no "turn off" option in the portal. I assume you mean Delete?

=====

you much create either a free, MSDN or Personal account

you must create....

=====

Install Docker for Windows CE.

This should be called Docker Desktop for Windows

=====

All the scripts and files in the labs are found in the sql2019 folder.

What about your notebooks and any scripts from Anna?

Also this should be the sql2019lab folder. I fixed this in my setup instructions as well

=====

**Comment by BuckWoody** [comment]
Great comments! I've made the fixes suggested.
