### ISSUE TITLE
Feedback for Module 6 from SQLG2C

### ISSUE THREAD

**Issue by rgward** [microsoft/sqlworkshops#114]
Feedback for Module 6 of SQLG2C at https://github.com/microsoft/sqlworkshops/blob/master/SQLGroundToCloud/sqlgroundtocloud/06-WhatToUseWhen.md

======

General comments and thoughts:

I like the scenarios but I'd like mix in requirements for

Data Classification
Availability (ADR)
Linux and Containers

For Contoso you might even include something about surface area so they must choose Managed Instance vs just Azure SQL DB.

I also wonder whether we should exclude any "application" stuff like "Must be user-friendly on mobile devices" and stick to just "data" requirements?

=====

In this workshop you'll cover using SQL Server both on-premises and in-cloud configurations, as well as hybrid applications as a solution for data processing. In each section you'll get more references, which you should follow up on to learn more. Also watch for links within the text - click on each one to explore that topic.

Does this Module require you to have gone through Modules 1-5?

I didn't understand if this statement was being used to introduce this module or the overall workshop?

=====

some sort of design software

can we provide any examples? Visio?

=====

03 Architecture Design Session (ADS): An initial layout of the technology options and choices for a preliminary solution

Do we use ADS any more as it may confuse with Azure Data Studio

=====

Enable B2B systems

I honestly had to lookup B2B to make sure I knew what that meant

=====

Project Goals and Constraints

Do you expect the workshop users to ask us as instructors more details on these goals and constraints? For example, does "Increase Performance" mean Increase query performance?

What does Cloud Integration mean?

Modernize to a newer SQL version

What does "newer" mean since we don't know what version they are on?

=====

Project Goals

Move everything to Cloud
Multi-Cloud strategy desired - standards-based
All client apps should be available worldwide
Server-side should be API's by default

Multi-Cloud strategy? Do you mean work with multiple cloud providers like Azure, AWS, ...? If so, that conflicts with their process to "a cloud provider".

I'm not even sure what "Server-side should be API's by default" means? I can think of several things it might mean but it might lead to more confusion than what is meant for the exercise.

=======

Project Constraints

High Security and Auditing capabilities required
International Compliance required
Access Tracking required
Must be user-friendly on mobile devices

What is "Access Tracking required" mean?

=======

Steps

Open your Architecture Design Session (ADS) document and detail all technologies you have studied in this workshop, and list them out. (Order is not important during this step)
Next, write the problem element next to each technology that it could solve
Document any processes you should follow when using each technology

What resources should we provide them to choose technologies? Just choose from our workshop?

======

and there are mutiple technology and process choices

typo multiple

======

**Comment by BuckWoody** [comment]
Great comments. Addressed these for clarity, although some are left intentionally vague as described in the assignment.
