### ISSUE TITLE
link broken final module BDC

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/sqlworkshops#12]
At the very bottom

"Steps
Open this reference, and follow the instructions you see for the Service Endpoints section. This shows the addresses and ports exposed to the end-users."

The link is broken. It points here "https://github.com/Microsoft/sqlworkshops/blob/master/sqlserver2019bigdataclusters/SQL2019BDC/href"

**Comment by BuckWoody** [comment]
Found, fixed. Thanks for the catch!
