### ISSUE TITLE
Add in new screenshot for DMA tool on Module 4 Activity 3

### ISSUE THREAD

**Issue by rgward** [microsoft/sqlworkshops#121]
In Activity 3 of Module at https://github.com/microsoft/sqlworkshops/blob/master/AzureSQLLabs/Lab-DatabaseDiscoveryAndAssessmentForMigratingToAzure.md#Activity-3

I recommend you put in the new DMA screenshot to reflect the Assessment Type. The default is Database Engine which we are using but just to avoid any confusion put in the new screenshot of this and add in the instructions to keep default type for Assessment Type.

**Comment by amthomas46** [comment]
I guess there is a new version, fixed in my branch
