### ISSUE TITLE
Review sequence of steps for Module 4 Activity 1

### ISSUE THREAD

**Issue by rgward** [microsoft/sqlworkshops#122]
In Activity 1 for Module 4 at https://github.com/microsoft/sqlworkshops/blob/master/AzureSQLLabs/Lab-DatabaseDiscoveryAndAssessmentForMigratingToAzure.md#Activity-1

You list out these steps

For assessment tools, select Azure Migrate: Database Assessment, then select Add tool.
For migration tools, select Azure Migrate: Database Migration, and then select Add tool. Azure Migrate is now set up for you to use. In the next activity, you'll use some of the tools you added to assess and migrate Tailspin Toys to Azure.

Please review those screens. I think I had to hit Next instead of Add Tool and then when I was done I had to select Add Tool.

**Comment by amthomas46** [comment]
Good catch. Confirmed and updated in my branch
