### ISSUE TITLE
Clarify how users find out what hands-on-lab-SUFFIX is...

### ISSUE THREAD

**Issue by rgward** [microsoft/sqlworkshops#123]
We use the term hands-on-lab-SUFFIX in Module 4 and 5 activities but never say how someone figure out what this is. I think we should say perhaps somewhere at the top of each Module that for instructor led labs you will be provided this or use the one you created in prereqs for Module 4 and 5.

**Comment by amthomas46** [comment]
How's this, added to all places where SUFFIX is mentioned:  

> **Note:**  
> If you were provided with an environment for these labs, the "SUFFIX" part of the **hands-on-lab-SUFFIX** will be used in several portions of the lab. You should note this value from the credentials provided. Any time "SUFFIX" is referenced, use this number. **Do not use other "SUFFIX" values or you will disrupt another attendees environment.**
