### ISSUE TITLE
Clarify what status looks like for initial online Migration in Module 5 Lab 1 Activity 6

### ISSUE THREAD

**Issue by rgward** [microsoft/sqlworkshops#124]
In Module 5 Lab 1 Activity 6 on Step 16 at https://github.com/microsoft/sqlworkshops/blob/master/AzureSQLLabs/Lab-MigratingToAzureSQLManagedInstance.md#Activity-6.

It says the status should say Log Files Uploading when you know to move the next task. My status says Log Shipping in progress but when you click the Database the backup is restored. We should clarify that the exact status should look like here.

**Comment by amthomas46** [comment]
Added note that once you see either you're god to move on. Thanks!
