### ISSUE TITLE
There is no refresh button for Complete Cutover in Module 5 Lab 1 Activity 7

### ISSUE THREAD

**Issue by rgward** [microsoft/sqlworkshops#125]
the lab states in this Activity at https://github.com/microsoft/sqlworkshops/blob/master/AzureSQLLabs/Lab-MigratingToAzureSQLManagedInstance.md#Activity-7

Note:
This will take between 10-30 minutes, so it might be a good time to take a break, or to review what you've done so far. Sometimes the progress is delayed, you can select Refresh to update manually.

But there is no refresh button to do this manually. My Cutover screen never came back to Completed but in a second portal window I monitored the status of the Migration Project and it said completed but the original Cutover screen was not updated yet.

**Comment by amthomas46** [comment]
I added a note about how to do this, I will test to confirm
