### ISSUE TITLE
SQL MI instance for instructor led labs clarification in Module 5 Lab 1 Activity 8

### ISSUE THREAD

**Issue by rgward** [microsoft/sqlworkshops#126]
In Module 5 Lab 1 Activity 8 at 

it says

In the Connect to Server dialog, enter the following:

Server name: Enter the fully qualified domain name of your SQL managed instance, which you copied from the Azure Cloud Shell in a previous task

But for instructed led labs they will not have done this. Just to help make it clear you might add a blurb that says instructor led labs will provide you the name of the FQDN to use for SQLMI

**Comment by amthomas46** [comment]
Added a note, good catch!
