### ISSUE TITLE
Clarify what IP, user, and password are need for Module 5 Lab 1 Activity 9

### ISSUE THREAD

**Issue by rgward** [microsoft/sqlworkshops#127]
We probably should clarify a bit for Module 5 Lab 1 Activity 9 at https://github.com/microsoft/sqlworkshops/blob/master/AzureSQLLabs/Lab-MigratingToAzureSQLManagedInstance.md#Activity-9

Step 13 says to update the IP and password from the SQL 2008 VM but you should probably clarify which IP, public or Private. And also remind them to use the same SQL account WorkshopUser and password as from a previous lab.

**Comment by amthomas46** [comment]
fixed
