### ISSUE TITLE
Clarify how to replace the server name for app in Module 5 Lab 1 Activity 9

### ISSUE THREAD

**Issue by rgward** [microsoft/sqlworkshops#129]
In Module 5 Lab 1 Activity 9 at https://github.com/microsoft/sqlworkshops/blob/master/AzureSQLLabs/Lab-MigratingToAzureSQLManagedInstance.md#Activity-9

On Step 18 it says

Now, in order to have the app run with the data in SQL MI, update appsettings.json by replacing the SQL 2008 VM IP with the fully qualified domain name for your MI (something like sqlmi.fdsor39943LabExercise-234j3oj4.database.windows.net). Then, replace WorkshopUser with sqlmiuser.

Someone may not Now, in order to have the app run with the data in SQL MI, update appsettings.json by replacing the SQL 2008 VM IP with the fully qualified domain name for your MI (something like sqlmi.fdsor39943LabExercise-234j3oj4.database.windows.net). Then, replace WorkshopUser with sqlmiuser.

What they should do is replace the entire Server=tcp:<IP>,1433 with the MI FQDN. Someone may just substitute the IP address for the MI FQDN. While that technically works I would have them just use the FQDN. The workshop is using the TCP syntax because there is no DNS resolution to the SQL 2008 VM.

Also this doesn't instruct the user to be sure and use the password for sqlmiuser which may not the same as WorkShopUser.

**Comment by amthomas46** [comment]
Updated, I will test to confirm all works. 

Thank you, I learned something here :-)
