### ISSUE TITLE
Small typo in BDC workshop

### ISSUE THREAD

**Issue by rgward** [microsoft/sqlworkshops#130]
Found a small typo in the BDC workshop on this page

https://github.com/microsoft/sqlworkshops/blob/master/sqlserver2019bigdataclusters/SQL2019BDC/01%20-%20The%20Big%20Data%20Landscape.md

Activity: Review HDFS Tutorial

There are two primary storage concepts you will work with in SQL Server Big Data Clusters: the HDFS layer, and SQL Server. Fro HDFS, it's important to know the basics of how it works.

**Comment by BuckWoody** [comment]
Fixed. Thanks for the catch!
