### ISSUE TITLE
Type in brief description of Livy

### ISSUE THREAD

**Issue by chrisadkin** [Microsoft/sqlworkshops#14]
You have 'Tob' submission, I suspect that Tob should be replaced with Job.

**Comment by BuckWoody** [comment]
Hey Chris - can you tell me which page that's on?

**Comment by chrisadkin** [comment]
This one https://github.com/Microsoft/sqlworkshops/tree/master/sqlserver2019bigdataclusters

**Comment by BuckWoody** [comment]
Fixed. Thanks for the catch!
