### ISSUE TITLE
Activity 2. 1 in 00-prerequisites.md

### ISSUE THREAD

**Issue by jeroenterheerdt** [microsoft/sqlworkshops#142]
Activity 2.1 says you need to install all features for SQL 2019 including PolyBase (stand-alone). PolyBase (stand-alone) is not there in RC1 - it is called 'PolyBase Query Service for External Data' now. Also, I think we should say that we need all features for 'Database Engine Services' installed, which would exclude 'Analysis Services' and all the Shared Features. Although I doubt if we need 'Data Quality Services' and 'Full-Text and Semantic Extractions for Search'.

**Comment by jeroenterheerdt** [comment]
@BuckWoody

**Comment by BuckWoody** [comment]
Agreed - I'll make those semantic changes. I do "all features" since I sometimes vector off to questions and demos in the class, and this allows us not to have to wait for installs in class. (I am assuming this is in the G2C course, not the BDC one? We have a few 00-prerequisites in the repo :)
