### ISSUE TITLE
Resource 'JumpBox-ip' was disallowed by policy Module4and5Prerequisites

### ISSUE THREAD

**Issue by jeroenterheerdt** [microsoft/sqlworkshops#144]
After clicking on 'purchase'  (step 6 in Module4and5Prerequisites) I get a "Resource 'JumpBox-ip' was disallowed by policy" error effectively stopping me from deploying pre-reqs for module 4 and 5.

**Comment by jeroenterheerdt** [comment]
@amthomas46

**Comment by amthomas46** [comment]
Interesting. I'll have to look more into this one. I've deployed like this without issues. I wonder if it's a subscription thing?

**Comment by jeroenterheerdt** [comment]
maybe - I am using MS internal subscription. Let me check on another.

**Comment by jeroenterheerdt** [comment]
yep, just verified it works fine using another subscription. Closing.

**Comment by amthomas46** [comment]
OK cool - good to know. thank you!
