### ISSUE TITLE
02_Security.md can benefit from some more layout

### ISSUE THREAD

**Issue by jeroenterheerdt** [microsoft/sqlworkshops#146]
Please consider highlighting column names and function names with `this` to improve readability.

**Example of current text:** 
Notice the results have columns for information_type_id and label_id. These are GUID values that you can use instead of just string values. Your organization's data catalog system may require a unique ID for tracking classification metadata. Remember the NEWID() T-SQL function can be used to generate unique GUID values. The SSMS tool generates information_type_id and label_id values.

**Example of improved text:**
Notice the results have columns for `information_type_id` and `label_id`. These are GUID values that you can use instead of just string values. Your organization's data catalog system may require a unique ID for tracking classification metadata. Remember the `NEWID()` T-SQL function can be used to generate unique GUID values. The SSMS tool generates `information_type_id` and `label_id` values.

**Comment by jeroenterheerdt** [comment]
@rgward some ideas to improve readability in your MD files.

**Comment by rgward** [comment]
Good suggestions. I'll fix these in the next PR

**Comment by rgward** [comment]
fixed in latest PR
