### ISSUE TITLE
Lab-MigratingToAzureSQLManagedInstance.md

### ISSUE THREAD

**Issue by jeroenterheerdt** [microsoft/sqlworkshops#150]
Activity 6, step 7 says to `Target Azure SQL Managed Instance: Select the sqlmi-SUFFIX instance`. In the environment there are only `mi-SUFFIX` instances available, so I think this is a simple mismatch between docs and code that deploys the instances.

**Comment by jeroenterheerdt** [comment]
@amthomas46

**Comment by amthomas46** [comment]
Yes - this is a good one, I will update. I received that comment from a few folks in class too!
