### ISSUE TITLE
Lab-MigratingToAzureSQLManagedInstance.md ApplicationIntent=READONLY does not work. 

### ISSUE THREAD

**Issue by jeroenterheerdt** [microsoft/sqlworkshops#151]
After following the steps in Exercise 3 the application page still shows READ_WRITE, no READ_only. This are my connection strings:
`
"ConnectionStrings": {
    "TailspinToysContext": "Server=tcp:mi-xxxx.database.windows.net,1433;Database=TailspinToys;User ID=xxxx;Password=xxxx;Trusted_Connection=False;Encrypt=True;TrustServerCertificate=True;",
    "TailspinToysReadOnlyContext": "Server=tcp:mi-xxxxdatabase.windows.net,1433;Database=TailspinToys;User ID=xx;Password=xxxxx;Trusted_Connection=False;Encrypt=True;TrustServerCertificate=True;ApplicationIntent=ReadOnly;"
  }`

**Comment by jeroenterheerdt** [comment]
@amthomas46

**Comment by amthomas46** [comment]
Hi Jeroen, good call out! In the workshop, this lab is optional. It works if you **don't use the lab environment provided**. The reason for that is the lab environments leverage Instance Pools which only support General Purpose, which means the read-scale endpoint is not applicable here. If you go through the workshop self-paced and deploy yourself, you'll deploy a BC instance which will make this work. Does that make sense?

**Comment by jeroenterheerdt** [comment]
Ah that makes a lot of sense :) so, maybe just add that note to the markdown?
