### ISSUE TITLE
Replace "Docker" with "Container Runtime" and "Kubernetes" with "Container Orchestration (such as Kubernetes or OpenShift" in Ground-To-Cloud and Big Data Clusters courses

### ISSUE THREAD

**Issue by BuckWoody** [microsoft/sqlworkshops#154]
I'll start making these changes in the BDC modules, and leave it to the discretion of the other authors to make changes in their modules and courses.

**Comment by rgward** [comment]
I'm find with changing Docker with Container Runtime and logos but I think it makes sense to stick to Kubernetes because all the container orchestration distributions are based on k8s.

**Comment by rgward** [comment]
I've made changes in my decks and content where appropriate for just containers instead of Docker

**Comment by BuckWoody** [comment]
Agree on Kubernetes - I still say "orchestration" but then I add (such as Kubernetes) to stay safe. :) Yours look fine, and I think mine are all up to date, so I'll close this one.
