### ISSUE TITLE
Migrate project looks to have single namespace

### ISSUE THREAD

**Issue by hfxdklee** [microsoft/sqlworkshops#163]
The instructions in Activity 1 to use the migrate project name 'MigrateTailspinToys' appears to not work en mass. The deployment fails if multiple people are attempting to use the name. If a unique name is entered, the deployment completes successfully as expected.

**Comment by rgward** [comment]
here is the link for the page where we had this problem https://github.com/microsoft/sqlworkshops/blob/master/AzureSQLLabs/Lab-DatabaseDiscoveryAndAssessmentForMigratingToAzure.md#Activity-1.

**Comment by amthomas46** [comment]
Closing issue, migrate project was never supposed to be completed in the day long version of SQL Ground to Cloud. Will work fine for self study.
