### ISSUE TITLE
Typo on 02_IntelligentPerformance.md

### ISSUE THREAD

**Issue by joesackmsft** [microsoft/sqlworkshops#172]
https://github.com/microsoft/sqlworkshops/blob/sql2019workshop/sql2019workshop/sql2019wks/02_IntelligentPerformance.md

Small typo here:

SQL Server: Wait Statistics/Patch latch Waits/Waits started per second. Adjust the scale to 0.01

"Page latch" instead of "Patch latch" and make sure to bold all of "Waits started per second."

**Comment by rgward** [comment]
this will be fixed in the next PR
