### ISSUE TITLE
Docker Windows - Replication Lab - can't run db-init.sh

### ISSUE THREAD

**Issue by paschott** [microsoft/sqlworkshops#182]
When using Docker for Windows on the Replication Lab, I get the following error after issuing a "docker-compose up" command.

Step 3/4 : RUN chmod +x /db-init.sh
 ---> Running in 3606a883e723
chmod: changing permissions of '/db-init.sh': Operation not permitted
ERROR: Service 'db1' failed to build: The command '/bin/sh -c chmod +x /db-init.sh' returned a non-zero code: 1

Tried tweaking this to the ubuntu builds but get the same error. Is there something that I need to do within the containers to enable this or a different command to run?

Edit: Changed the "Dockerfile" for these to comment out the "RUN chmod" line and it starts now. I may have missed that in the documentation when running on Docker for Windows.

**Comment by rgward** [comment]
We will investigate this

**Comment by rgward** [comment]
this problem occurs due to sql2019 GA now being non-root containers. I have a fix committed and will show up in our next PR
