### ISSUE TITLE
Add shortcut to folder in labs

### ISSUE THREAD

**Issue by marc-kent** [microsoft/sqlworkshops#191]
Open Powershell (or CMD) in a given folder by navigating to the folder in Explorer and then typing "Powershell" (or "CMD") into the address bar and then hitting Enter.

NB:  Doesn't work for network shares.

**Comment by BuckWoody** [comment]
Hello Marc - Which course/module is this? If you can paste the link to the page where you see this, we can get it to the right author. I don't believe we use any network shares in our courses, but I could be wrong.

**Comment by marc-kent** [comment]
Hey Buck!
Sorry, this was Bob Ward's SQL 2019 Precon day at PASS Summit last
Tuesday.  He asked me to raise an issue to remind him about this (I
actually taught him something!) so he could include it in future
presentations.
I hadn't used GIT up to this point, I registered just to raise the issue
for Bob, no doubt I did it wrong.
Thanks,
Marc

**Comment by rgward** [comment]
Thanks for the tip. I'll look at incorporating this in future revs of the course

**Comment by marc-kent** [comment]
No problem!
