### ISSUE TITLE
SQL Server 2019 service won't start

### ISSUE THREAD

**Issue by fazalWahid56** [microsoft/sqlworkshops#193]
I just downloaded and install SQL server 2019 on my windows 10. But i was not able to connect to it via SSMS.

I went to the services and saw that "SQL Server (MSSQLSERVER)" service is not started. When i start the service it shows message

`The sql server mssqlserver service on local computer started and stopped`

I checked for event log and there is an error 
`_SQL Server is terminating a system or background task Logwriter Task due to errors in starting up the task (setup state 8)._`

In SQL ErrorLog I can see following error:
`Error: 17312, Severity: 16, State: 1. 2019-11-04 01:12:49.11 spid2s SQL Server is terminating a system or background task AzureLeaseRenewalTask due to errors in starting up the task (setup state 8). 2019-11-04 01:12:49.11 spid1s CImageHelper::Init () Version-specific dbghelp.dll is not used 2019-11-04 01:12:49.11 spid2s Error: 28709, Severity: 16, State: 19. 2019-11-04 01:12:49.11 spid2s Dispatcher was unable to create new thread. 2019-11-04 01:12:49.13 spid1s ***Stack Dump being sent to C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\LOG\SQLDump0007.txt 2019-11-04 01:12:49.13 spid1s SqlDumpExceptionHandler: Process 1 generated fatal exception c0000005 EXCEPTION_ACCESS_VIOLATION. SQL Server is terminating this process.`

**Comment by BuckWoody** [comment]
Hello! This repo deals with courses, not the product itself. Suggest you contact support here: https://support.microsoft.com/en-us/contactus/
