### ISSUE TITLE
Book reference

### ISSUE THREAD

**Issue by ArmandoLacerda** [microsoft/sqlworkshops#198]
Hi Bob, I got a copy of "SQL Server 2019 Revealed" at MS Ignite a couple weeks ago. I am following along the exercises on chapter 2 and I can't find the scripts (both SQL and CMD) in this repo, in particular the "underestimated memory grant" and the "excessive memory grant" sections in chapter 2. 
Should I expect these files to be made available later? 
Missing files:
- iqp_rowmodemfg.sql
- adjustrg.cmd
- adjustrg.sql
- rowmode_mgf.cmd
- rowmode_mgf.sql
- turn_on_mgf.cmd
- turn_on-mgf.sql
- adjustrgback.cmd
- restore_orderhistory_state.cmd

Thanks.

**Comment by rgward** [comment]
Where did you look for the scripts? I have a copy of the book github repo at https://github.com/microsoft/bobsql/tree/master/sql2019book.

**Comment by rgward** [comment]
I found out the publisher has not yet posted my scripts to the apress github repo. Should be there soon. For now, use https://github.com/microsoft/bobsql/tree/master/sql2019book.
