### ISSUE TITLE
sqlserver2019bigdataclusters/README.md Line 81 typo - Conainer Orechestration

### ISSUE THREAD

**Issue by abair34** [microsoft/sqlworkshops#200]
Sorry, I previously submitted a pull request to fix this rather than an issue.

There's a typo on line 81 of  sqlserver2019bigdataclusters/README.md

<tr><td><i>Conainer Orechestration (such as Kubernetes)</i></td><td>Management, control plane for Containers</td></tr>

s/b:
  <tr><td><i>Container Orchestration (such as Kubernetes)</i></td><td>Management, control plane for Containers</td></tr>

**Comment by rgward** [comment]
Thank you I'll take a look

**Comment by rgward** [comment]
Sorry Buck this is in your workshop

**Comment by BuckWoody** [comment]
Corrected all spelling errors. There were a lot!
