### ISSUE TITLE
hyperlink redirect

### ISSUE THREAD

**Issue by mwdarab** [microsoft/sqlworkshops#206]
Under [About this Workshop](https://github.com/Microsoft/sqlworkshops/tree/master/sqlserver2019bigdataclusters#about-this-workshop) at the end it says, "You can view all of the source files for this workshop on this GitHub site, along with other workshops as well. Open this link in a new tab to find out more" 

But the hyperlink points to the same page.  i.e. https://github.com/Microsoft/sqlworkshops/tree/master/sqlserver2019bigdataclusters

**Comment by BuckWoody** [comment]
Right - if the page has been opened in "Pages" or maybe in a converted PDF, etc they aren't in the github base, they are in a rendered site. That link will bring them to the right location. :)
