### ISSUE TITLE
Activity 4: Install Azure CLI -> choco install azure-cli

### ISSUE THREAD

**Issue by SQLvariant** [Microsoft/sqlworkshops#22]
Please have a look at the `azure-cli` chocolatey package.  I believe you can use `choco install azure-cli` to replace the manual step in "Activity 4: Install Azure CLI"

https://github.com/Microsoft/sqlworkshops/blob/master/sqlserver2019bigdataclusters/SQL2019BDC/00%20-%20Prerequisites.md

**Comment by BuckWoody** [comment]
Corrected. Thanks!
