### ISSUE TITLE
OpenShift

### ISSUE THREAD

**Issue by chrisadkin** [microsoft/sqlworkshops#225]
Can you please explain to the audience in this section what OpenShift actually is, something along the lines of its full name is OpenShift Container Platform and it is a commercially supported PaaS based on Kubernetes from RedHat. Can you also mention why this is important, i.e. regulated industries will only use software thaty comes with a support agreement.

**Comment by BuckWoody** [comment]
I think I can find that section - if you don't mind, put the page link in so I can make sure I am editing the right thing. The Issue feature in github does not have the page linked. :)
