### ISSUE TITLE
Activity 8: Install Azure Data Studio and Extensions -> choco install azure-data-studio

### ISSUE THREAD

**Issue by SQLvariant** [Microsoft/sqlworkshops#23]
Please have a look at the `azure-data-studio` chocolatey package.  I believe you can use `choco install azure-data-studio` to replace the manual step in "Activity 8: Install Azure Data Studio and Extensions"

https://github.com/Microsoft/sqlworkshops/blob/master/sqlserver2019bigdataclusters/SQL2019BDC/00%20-%20Prerequisites.md

**Comment by BuckWoody** [comment]
Fixed. Thank you!
