### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by mwdarab** [microsoft/sqlworkshops#241]
Location: https://github.com/microsoft/sqlworkshops/tree/master/k8stobdc#-----learning-objectives

Second bullet point: "Hardware considerations for setting up a production Kubernetes Cluster on -remises". The last word should read **premises**.

Last paragraph, “Solution Architects, to understand how to put design an end-to-end solution” **Remove “put”**

**Comment by BuckWoody** [comment]
Corrected. Thanks for the catch.
