### ISSUE TITLE
SQL Express Distribution agreement

### ISSUE THREAD

**Issue by jwarner777** [microsoft/sqlworkshops#256]
In the SQL Server 2019 Express edition License_expr.rtf file there are no longer any Distribution Requirements or Distribution Restrictions.  It appears you can no longer legally distribute Sql Server 2019?  
File is located here: SQL Server 2019\Express\SQLEXPRADV_x64_ENU\1033_ENU_LP\x64\1033

Since its a RTF it cannot be uploaded to the page.

These sections exist in every SQL server edition until 2019.  The SQL 2019 Express edition reads the same as the SQL Server 2019 standard License and in fact there is also a Eval copy license in the SQl Server 2019 edition that did not exist in the 2014/2016/2017 License RTF files.  The word distribution only occurs 1 time in the 2019 License_expr.rtf file under the Transfer to Third Party section of the license file.  It also discusses that you need to license the system "License Model. The software is licensed based on the number of physical and/or virtual cores in the server." which SQL Express does not have.

Missing sections that allow for distribution from prior licenses:
a.	Distributable Code.
i.	Right to Use and Distribute.  If you comply with the terms below:
•	You may copy and distribute the object code form of the software (“Distributable Code”) in programs you develop;
•	You may combine the object code form of the Distributable Code with your programs to develop a unified web solution and permit others via online methods to access and use that unified web solution, provided that the Distributable Code is only used as part of and in conjunction with your programs; and
•	You may permit distributors of your programs to copy and distribute the Distributable Code as part of those programs.

ii.	Distribution Requirements. For any Distributable Code you distribute, you must
•	add significant primary functionality to it in your programs;
•	for any Distributable Code having a filename extension of .lib, distribute only the results of running such Distributable Code through a linker with your program;
•	distribute Distributable Code included in a setup program only as part of that setup program without modification;
•	require distributors and external end users to agree to terms that protect it at least as much as this agreement; 
•	display your valid copyright notice on your programs; and
•	indemnify, defend, and hold harmless Microsoft from any claims, including attorneys’ fees, related to the distribution or use of your programs.

iii.	Distribution Restrictions. You may not
•	alter any copyright, trademark or patent notice in the Distributable Code;
•	use Microsoft’s trademarks in your programs’ names or in a way that suggests your programs come from or are endorsed by Microsoft;
•	distribute Distributable Code to run on a platform other than the Windows platform;
•	include Distributable Code in malicious, deceptive or unlawful programs; or
•	modify or distribute the source code of any Distributable Code so that any part of it becomes subject to an Excluded License. An Excluded License is one that requires, as a condition of use, modification or distribution, that
•	the code be disclosed or distributed in source code form; or
•	others have the right to modify it.

**Comment by BuckWoody** [comment]
This is an "Issues" site for content on this repository. I think you're looking for Microsoft Support.

**Comment by jwarner777** [comment]
It has been confirmed that Microsoft has put the wrong License agreement in for SQL Server Express 2019 in a few weeks a new version will be released that will fix the SQL Express License agreement.
