### ISSUE TITLE
Typos and Wording Suggestions Part II

### ISSUE THREAD

**Issue by jamiere-msft** [Microsoft/sqlworkshops#37]
General comment:  Not sure if it proper to bold the usage of sqlcmd throughout this section.  It is currently in bold for the first usage.

**2.0 Connect to SQL Server**
**Activity: Connect to SQL Server**
- Step #2 - Add a ":" after "sudo)"
- Step #3 - Add a ":" after "be successful"
- Step #2 - Rephrase to "Your version information may be different depending on the version of the workshop and SQL Server."
**2.1 Restore a Database Backup**
- Step #3 - Add a ":" after "**step2copy_backup_into_container.sh**"

**Activity: Execute SQL Server Queries**
- Step #2 - Add a ":" after "across your screen like this"
- Step #3 - Add a ":" after "look like the following"
- Step #4 - Add a ":" after "something similar to this"
- Step #4 - The last paragraph is not indented as far as the other paragraphs
- Step #4, last Paragraph - Rephrase to "The third batch provides information ... has consumed"
- Step #5 - Add a ":" after "a prompt like this"
- Step #5 - Rephrase "By typing in a query and hitting Enter, then typing in the keyword GO and hit Enter again to execute a query."

**Comment by rgward** [comment]
Jamie, I fixed almost all of these. In some cases they didn't apply anymore based on buck's changes
