### ISSUE TITLE
Extended events do not capture CREATE and ALTER LOGIN statements

### ISSUE THREAD

**Issue by wasim-sayyad** [microsoft/sqlworkshops#46]
In SQL server 2012 and 2016, **CREATE LOGIN** and **ALTER LOGIN** statements are not getting captured by Extended events.

Is that bug or intentional?

Any alternative to capture same in SQL server in-premises environments ?

Thank you,
wasim_sayyad@hotmail.com

**Comment by BuckWoody** [comment]
Sorry - this is a location to enter bugs on these courses. If you have specific questions on products, go here: https://stackoverflow.com/questions/tagged/sql-server
