### ISSUE TITLE
sqlserver2019bigdataclusters - Wrong URL for HDFS hyperlink

### ISSUE THREAD

**Issue by tnbarkhouse** [microsoft/sqlworkshops#50]
In the "BDC: Storage Pool" section, https://github.com/microsoft/sqlworkshops/blob/master/sqlserver2019bigdataclusters/SQL2019BDC/02%20-%20SQL%20Server%20BDC%20Components.md#bdc-storage-pool , the table following "These components are used in the Storage Pool of the SQL Server big data cluster:" has a value of "HDFS" but it links to https://kubernetes.io/docs/concepts/overview/components/ .

**Comment by BuckWoody** [comment]
Corrected to https://www.hdfstutorial.com/hdfs-tutorial-guide/ - thanks for the catch.
