### ISSUE TITLE
CTP 3.1 - Update

### ISSUE THREAD

**Issue by mwdarab** [microsoft/sqlworkshops#52]
Under the "[Control Plane: Controller Service](https://github.com/microsoft/sqlworkshops/blob/master/sqlserver2019bigdataclusters/SQL2019BDC/02%20-%20SQL%20Server%20BDC%20Components.md#control-plane-controller-service)" section: You should remove "and the Cluster Administration Portal." as that feature was removed in **CTP 3.1.**

**Comment by BuckWoody** [comment]
Fixed, although watch this space. :)
