### ISSUE TITLE
two typos in 01_IntelligentPerformance.md for sql2019lab

### ISSUE THREAD

**Issue by amthomas46** [microsoft/sqlworkshops#53]
https://github.com/microsoft/sqlworkshops/blob/rgward/sql2019lab/01_IntelligentPerformance.md

Typo 1: in "1.0 The Solution"

	"processing" I think should be capitalized

Typo 2: in "Activity: SQL Server Intelligent Query Processing"

	The WideWorldImporters database example was created using SQL Server 2016 which has a default database compatibility level of 130. When a database is restored from a previous version oF SQL Server, the compatibility level of the database is preserved to help reduce the risk of upgrades.
	
	Typo "oF"

@rgward

**Comment by rgward** [comment]
Fixed in rgward branch
