### ISSUE TITLE
Suggested reword in 01_IntelligentPerformance.md for sql2019lab

### ISSUE THREAD

**Issue by amthomas46** [microsoft/sqlworkshops#54]
https://github.com/microsoft/sqlworkshops/blob/rgward/sql2019lab/01_IntelligentPerformance.md

Suggested reword in 01_IntelligentPerformance.md

In the guide for getting set up with Azure Data Studio notebooks, the instructions say
"Use the File menu to open up the iqp_tablevariabledeferred.ipynb notebook and go through all the steps."
	
I might instead recommend something like….

'Use the File > Open Folder menu to open up the folder sql2019lab. Now, in Azure Data Studio, you can select the piece of paper icon on the left-hand taskbar to navigate through the folder. As you go through the labs, you can find the .ipynb files in their respective folders (e.g. the notebook file for 01_IntelligentPerformance is in sql2019lab/01_IntelligentPerformance/iqp/iqp_tablevariabledeferred.ipynb)."

Why?  
That way, in the following labs, they don't have to keep opening each file, they can just navigate using the built in file explorer.  

@rgward

**Comment by rgward** [comment]
Great suggestion. I've used your suggestion and made changes like this for Module 1, 3, and 4,  Please pull latest from rgward branch and let me know is this works. If you agree, then please close out this issue

**Comment by amthomas46** [comment]
Nice! I like the screenshot too.  One thing -  
"open up the iqp_tablevariabledeferred.ipynb notebook and go through all the steps> You can now use Azure Data Studio explorer to open up a notebook or script without exiting the tool." just a ">" typo instead of a period in Module 1.

**Comment by amthomas46** [comment]
Feel free to close the issue after you see the note about ">" typo. Wasn't sure if I closed it if you would still get the notification. Thanks.

**Comment by rgward** [comment]
Crud, I thought I caught those. I had them fixed in 3 and 4 but not 1. Thanks for the catch. Fixed now so closing
