### ISSUE TITLE
sql2019lab module 2.1 missing Linux filepath

### ISSUE THREAD

**Issue by amthomas46** [microsoft/sqlworkshops#55]
In the setup for the lab, states that you should be able to use a Windows or Linux instance of SS2019.  

In https://github.com/microsoft/sqlworkshops/blob/rgward/sql2019lab/02_Security.md , but for Lab 2.1 for Step 2, only provide the filepath for Windows.  

Recommended change
Add a note below that says something like..  
Note: If you are using SQL Server on Linux, change the FILEPATH to `/var/opt/mssql/data`

@rgward , feel free to ping me if I can help on this one.

**Comment by amthomas46** [comment]
Also, in step 4, add a similar note to "/var/opt/mssql/data/*.sqlaudit"

**Comment by rgward** [comment]
Fixed in latest branch update. I also made changes in notebooks and scripts where any path was used
