### ISSUE TITLE
External data sources are not supported with type GENERIC.

### ISSUE THREAD

**Issue by davidma3768** [microsoft/sqlworkshops#57]
04_DataVirtualization, encountered error when create external data source on Azure SQL. Not sure if I missed any other steps. 

--SQL statement
CREATE EXTERNAL DATA SOURCE AzureSQLDatabase
WITH ( 
LOCATION = 'sqlserver://dmasql.database.windows.net',
PUSHDOWN = ON,
CREDENTIAL = AzureSQLDatabaseCredentials1
)
GO

-- Error message
Started executing query at Line 17
Msg 46530, Level 16, State 11, Line 1
External data sources are not supported with type GENERIC.
Total execution time: 00:00:00

**Comment by rgward** [comment]
David, this error can occur if you have not installed and enabled the Polybase feature in SQL Server 2019.

**Comment by rgward** [comment]
David, I believe you have this fixed now because Polybase was not installed and enabled and the services were not running. With that you are now working for the lab.
