### ISSUE TITLE
How to use a package in R which has two types of outputs(data and image) using Stored procedure in SQL and display the same as in screenshot from R-studio in SQL

### ISSUE THREAD

**Issue by soumyavinjam** [microsoft/sqlworkshops#65]
How to use a package in R which has two types of outputs(data and image) using Stored procedure in SQL and display the same as in screenshot from R-studio in SQL
<img width="960" alt="R_studio" src="https://user-images.githubusercontent.com/45124488/61625621-cadd0680-ac98-11e9-8b41-c0383575a24c.PNG">

**Comment by BuckWoody** [comment]
Sorry - best to post this is in a help chat. This is a place to enter bugs on the courses on this site. Thanks!
