### ISSUE TITLE
SQL Server 2019 Lab suggestions

### ISSUE THREAD

**Issue by kevchant** [microsoft/sqlworkshops#66]
Hi, I was asked to add suggestions from my review here so here they are:

For the Intelligence Performance module it might be worth reminding people not to run all the cells within the notebook at once.

For the Availability module it might be worth having a prepopulated copy of the gocowboys database available as a download to save people processing time. 

Also, worth mentioning to people if they are going to bonus they might want to keep an eye out for blocking issues when using the ALTER DATABASE statement, or get them to close everyting from the previous section first.

It might be worth telling people how much disk space they need for the gocowboys database in advance as well, especially if they are doing the bonus section.

For the Data Virtualization section it might be worth getting them to check that Polybase is definitely enabled before they look to connect to the Azure SQL database, just to be on the safe side.

I have had issues wit the Linux and Containers section. I suspect it may be resource related but I want to fully test before putting more details on here. In meantime might be testing on machines of various specs to see if that effects the running of the docker-compose.

Finally, it might be worth making sure people know that the slides are available, as they can be fairly useful for people.

Anyway, that's it for now.

**Comment by rgward** [comment]
Thanks for these suggestions. Let me look these over for further enhancements to the labs. I'd rather not provide a backup of the gocowboys db because there is no easy place to put a backup file for this.

**Comment by rgward** [comment]
Reopening this issue so I can track any changes i make per these suggestions. I should be able to address these over the next few weeks

**Comment by rgward** [comment]
Thanks for all of your suggestions. I've added several things to the readme per your suggestions. The one thing I didn't do was create backups of the gocowboys database. GitHub is not a great place to host a backup binary file so I've left the scripts so the user has to create and populate data.  You have a separate issue filed for Module 5
