### ISSUE TITLE
SQL Server 2019 Lab issue

### ISSUE THREAD

**Issue by kevchant** [microsoft/sqlworkshops#69]
As promised here's the issue I have been experiencing with the Linux and Containers section within the SQL Server 2019 Lab.

Sometimes I have noticed that when using docker-compose it freezes during the use of xpstar.dll. In addition. 

I also once encountered abn error saying that the replication agent had encountered an exception. However, after that error I reset Docker for WIndows  which allowed me to go further.

Once the Lab has loaded the replication snapshot does not always work. Which I suspect  is due more to the laptop I was using at the time as the job is set to run when the CPU is idle.

It might be worth testing for minimum specs as laptop in question had 4 cores. However, might just be easier to add an extra bit of text to say that if the snapshot has not being created than run the job manually instead.

**Comment by rgward** [comment]
Thanks for these comments. Hmmm, I never saw anything like this when I ran the lab over and over several times. The job should be run immediately not when the CPU is idle. I don't think having less cores is an issue. Can you post the output of the screen you get with these problems as the containers are run not in the background

**Comment by kevchant** [comment]
OK, laptop is being upgraded today however was still able to test. Here's a copy of the Synchronization Status when the containers are up and running but replication not completed. Let me know if you need anything more. I will try and replicate the xpstar.dll freeze later but I suspect the Docker reset may have resolved that one
![20190806 Synchronization status](https://user-images.githubusercontent.com/25753357/62518911-d993f380-b82a-11e9-8e55-99db3f56fd19.png)

**Comment by kevchant** [comment]
Here's a copy of the docker-compose output, the SQl Server Log  and the SQL Server Agent history for the Publisher instance as well
[dclog.txt](https://github.com/microsoft/sqlworkshops/files/3471417/dclog.txt)
[20190806 instance 1 SQL Agent History.log](https://github.com/microsoft/sqlworkshops/files/3471418/20190806.instance.1.SQL.Agent.History.log)
[20190806 instance 1 SQL Server log.log](https://github.com/microsoft/sqlworkshops/files/3471419/20190806.instance.1.SQL.Server.log.log)

**Comment by rgward** [comment]
I'm not sure about the config of our laptop but it looks like it is taking a very long time to startup the SQL Server containers. The db-init.sh script which is located in the db1 and db2 directory has a command of sleep 45s to allow both the SQL Server containers to startup. As a test can you change those to 120s to see if that gives plenty of time for the servers to startup and run the repl agent jobws?

**Comment by rgward** [comment]
Closing due to no repro and inactivity. Please reopen if you have more details and can try to change the sleep timings
