### ISSUE TITLE
Feedback for Module 3 of the SQL Ground to Cloud Workshop

### ISSUE THREAD

**Issue by rgward** [microsoft/sqlworkshops#83]
I'll review the notebooks from the activity in a separate GitHub issue if I find any, All of these comments are about this readme.md https://github.com/microsoft/sqlworkshops/blob/master/SQLGroundToCloud/sqlgroundtocloud/03-WorkingWithBigDataAndDataScienceBigDataClustersForSQLServer2019.md

This is a repeat paragraph from the previous one

In each module you'll get more references, which you should follow up on to learn more. Also watch for links within the text - click on each one to explore that topic.

----------

I kind of felt this paragraph was out of place in the sequence

Some industry examples of big data processing are in Retail (Demand Prediction, Market-Basket Analysis), Finance (Fraud detection, customer segmentation), Healthcare (Fiscal control analytics, Disease Prevention prediction and classification, Clinical Trials optimization), Public Sector (Revenue prediction, Education effectiveness analysis), Manufacturing (Predictive Maintenance, Anomaly Detection) and Agriculture (Food Safety analysis, Crop forecasting) to name just a few.

----------

A few comments on this intro

In this module you'll cover working with Data Science workloads with a focus on larger sets of data. Starting in SQL Server 2019, big data clusters allows for large-scale, near real-time processing of data over the HDFS file system and other data sources. It also leverages the Apache Spark framework which is integrated into one environment for management, monitoring, and security of your environment. This means that organizations can implement everything from queries to analysis to Machine Learning and Artificial Intelligence within SQL Server, over large-scale, heterogeneous data. SQL Server big data clusters can be implemented fully on-premises, in the cloud using a Kubernetes service such as Azure's AKS, and in a hybrid fashion. This allows for full, partial, and mixed security and control as desired.

1. I think you should mention the term data virtualization in this and what it means
2. What is the "hybrid fashion" example just so I'm clear. HDFS Tiering?

----------

Right after this paragraph I would put in a few hyperlinks on where to read more about containers and k8s

To control containers, a technology called Kubernetes is used for deployment, management and storage of a grouping of containers, called a Cluster.

----------

A SQL Server Big Data Cluster BDC can be deployed to three environments:

should be probably SQL Server Big Data Cluster (BDC)...

and I perhaps you should Introduce the BDC acronym term up earlier in the page?

---------

Which components can be interconnected?

These architectures are not mutually exclusive - you can install some components on-premises, and others as a service. Your connections can interconnect across these environments.

---------

When I read this, if I was a first time reader I might be a bit confused on "in addition to traditional..." since you have not described what the master instance is

In addition to traditional OLTP workloads, the SQL Server Big Data Cluster has three other uses that work with data at scale.

---------

A few comments on this paragraph

Using the Data Virtualization capability of PolyBase in SQL Server Big Data Clusters you create External Tables for data outside the Cluster

1) I would take a second and describe the basics of Polybase and put a link to the doc pages
2) I think somewhere we should identify that BDC deploys Polybae for you automatically (which can be a bit of a burden to this manually outside of BDC)
3) It is not always outside the cluster right? What about HDFS in the cluster? We don't really talk about how Polybase can access HDFS data in the storage pool in an optimized fashion (vs the classic method of Java MapReduce)

---------
 
This statement might confuse them if they haven't gone to your full course?

Using the Data Virtualization capability you saw in the 02 - BDC Components Module,...

---------

So this talks about how data is ingested into the data pool. How is it accessed then?

and the PolyBase statements can specify the target of the Data Pool. The SQL Server Instances in the Data Pool store the data in a distributed fashion across multiple databases, called Shards.

---------

You said there were 3 primary users but it was not clear what the other two were from this section

There are three primary uses for a large cluster of data processing systems for Machine Learning and AI applications.

--------

You made this statement but never really talked about how a user accesses the Data Storage data stores directly

These users can access the Data Pool and Data Storage data stores directly to query and assist with this task.

--------

You mentioned the App Pool in this sentence but never really defined what it is before this

or sent on to the App Pool where the Machine Learning Server is running

--------

I would put some type of link here on Spark and Jupyter notebooks (perhaps our own tutorial in the docs)

The Data Scientist has another option to create and train ML and AI models. The Spark platform within the Storage Pool is accessible through the Knox gateway, using Livy to send Spark Jobs. This gives access to the full Spark platform, using Jupyter Notebooks (included in Azure Data Studio) or any other standard tools that can access Spark through REST calls.

-------

**Comment by rgward** [comment]
Forgot to add this one. A typo on this sentence

Ad-hoc queries over larges sets of nomralized data are very useful for many scenarios

**Comment by BuckWoody** [comment]
Great comments! Fixed what I could, with an eye towards being able to cover this in an hour. I changed the note to tell them for a complete understanding to see the larger course. Some of the concepts mentioned in this bug are covered in the Notebooks.
