### ISSUE TITLE
Size the tlog for sql2019lab/03_Availability/adr/adr_recovery.sql

### ISSUE THREAD

**Issue by suresh-kandoth** [microsoft/sqlworkshops#98]
After running the DELETE operation in STEP 3, the tlog for this db grows to 40 GB. We should add some warning about this space requirement for the VM and also change the CREATE DATABASE script to pre-create the db for this size. In the workshop instructions we mention this now:
<<
If you have time use the T-SQL notebook adr_recovery.ipynb or T-SQL script adr_recovery.sql to see how ADR affects the recovery process. This bonus activity can take some time as a large number of modifications are needed to see a bigger effect on recovery. The scripts will create a database with a data file of 10Gb and transaction log of 10Gb so there is plenty of space for the activity.
>>

**Comment by rgward** [comment]
This is fixed in the next PR
