### ISSUE TITLE
For script sql2019lab/03_Availability/adr/adr_recovery.sql do we need step #5

### ISSUE THREAD

**Issue by suresh-kandoth** [microsoft/sqlworkshops#99]
When ADR is off and we attempt the delete, that gets aborted, so the table still has all the rows.
Do we need to drop and recreate the table again? We could go straight to set ADR ON and attempt the delete and shutdown the server?

**Comment by rgward** [comment]
Thanks Suresh for the suggestion. The initial test of this shows an issue getting this to demo correctly but I'll look at why and consider this for future revs of the labs
